<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateWeathersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('weathers', function (Blueprint $table) {
            $table->increments('id');
            $table->timestamps();
            $table->text('Outfalls')->nullable();
            $table->text('kmls')->nullable();
            $table->text('profiles')->nullable();
            $table->text('circular')->nullable();
            $table->text('mxrougs')->nullable();
            $table->text('mnrougs')->nullable();
            $table->text('mxenlefs')->nullable();
            $table->text('mienlefs')->nullable();
            $table->text('mxeloefs')->nullable();
            $table->text('mneloefs')->nullable();
            $table->text('mxaglefs')->nullable();
            $table->text('miaglefs')->nullable();
            $table->text('mxleths')->nullable();
            $table->text('mileths')->nullable();
            $table->text('totallgth')->nullable();
            $table->text('mxslope')->nullable();
            $table->text('mislope')->nullable();
            $table->text('dryweaflow')->nullable();
            $table->text('wetweaflow')->nullable();
            $table->text('groundweaflow')->nullable();
            $table->text('rdiiflow')->nullable();
            $table->text('exnalflow')->nullable();
            $table->text('exnaloutflow')->nullable();
            $table->text('floodloss')->nullable();
            $table->text('evaloss')->nullable();
            $table->text('exfiltionloss')->nullable();
            $table->text('lnitialvols')->nullable();
            $table->text('finalvols')->nullable();
            $table->text('conerrors')->nullable();
            $table->text('timeflows')->nullable();
            $table->text('dryweaflows')->nullable();
            $table->text('groundflows')->nullable();
            $table->text('rdiiflows')->nullable();
            $table->text('subments')->nullable();
            $table->text('grounwter')->nullable();
            $table->text('complexity_aquifers')->nullable();
            $table->text('complexity_snows')->nullable();
            $table->text('complexity_rdiigraphs')->nullable();
            $table->text('complexity_jundes')->nullable();
            $table->text('complexity_outdes')->nullable();
            $table->text('complexity_fldides')->nullable();
            $table->text('complexity_storaundes')->nullable();
            $table->text('complexity_conlinks')->nullable();
            $table->text('complexity_pumplinks')->nullable();
            $table->text('complexity_oriflinks')->nullable();
            $table->text('complexity_weirlinks')->nullable();
            $table->text('complexity_outlinks')->nullable();
            $table->text('complexity_transect')->nullable();
            $table->text('complexity_polluts')->nullable();
            $table->text('complexity_landus')->nullable();
            $table->text('totalcomity')->nullable();
            $table->text('raings')->nullable();
            $table->text('inventory_subments')->nullable();
            $table->text('inventory_aquifers')->nullable();
            $table->text('inventory_snows')->nullable();
            $table->text('inventory_rdiigraphs')->nullable();
            $table->text('inventory_jundes')->nullable();
            $table->text('inventory_outdes')->nullable();
            $table->text('inventory_fldides')->nullable();
            $table->text('inventory_storaundes')->nullable();
            $table->text('inventory_conlinks')->nullable();
            $table->text('inventory_pumplinks')->nullable();
            $table->text('inventory_oriflinks')->nullable();
            $table->text('inventory_weirlinks')->nullable();
            $table->text('inventory_outlinks')->nullable();
            $table->text('inventory_treunits')->nullable();
            $table->text('inventory_transect')->nullable();
            $table->text('inventory_conruls')->nullable();
            $table->text('inventory_polluts')->nullable();
            $table->text('inventory_landus')->nullable();
            $table->text('conves')->nullable();
            $table->text('divsionves')->nullable();
            $table->text('pumpves')->nullable();
            $table->text('ratingves')->nullable();
            $table->text('shapeves')->nullable();
            $table->text('strogves')->nullable();
            $table->text('tidalves')->nullable();
            $table->text('weirves')->nullable();
            $table->text('timeseries')->nullable();
            $table->text('timepatns')->nullable();
            $table->text('mxgroudev')->nullable();
            $table->text('mngroudev')->nullable();
            $table->text('mxvertev')->nullable();
            $table->text('mnvertev')->nullable();
            $table->text('mxdepth')->nullable();
            $table->text('midepth')->nullable();
            $table->text('flowunits')->nullable();
            $table->text('inftionmet')->nullable();
            $table->text('flowtingmet')->nullable();
            $table->text('linkoffsetsned')->nullable();
            $table->text('allowding')->nullable();
            $table->text('skipflowds')->nullable();
            $table->text('inertialing')->nullable();
            $table->text('defineflow')->nullable();
            $table->text('forcetion')->nullable();
            $table->text('variable')->nullable();
            $table->text('adjustment')->nullable();
            $table->text('conduit')->nullable();
            $table->text('surface')->nullable();
            $table->text('startingdate')->nullable();
            $table->text('endingdate')->nullable();
            $table->text('duration')->nullable();
            $table->text('antecedent')->nullable();
            $table->text('rain')->nullable();
            $table->text('reporttime')->nullable();
            $table->text('wettime')->nullable();
            $table->text('drytime')->nullable();
            $table->text('routingtime')->nullable();
            $table->text('minimumtime')->nullable();
            $table->text('avgtime')->nullable();
            $table->text('minimumcons')->nullable();
            $table->text('lgnoreofs')->nullable();
            $table->text('lgnoremelt')->nullable();
            $table->text('lgnoreter')->nullable();
            $table->text('lgnoreing')->nullable();
            $table->text('lgnorety')->nullable();
            $table->text('reportavgs')->nullable();
            $table->text('mxpipeter')->nullable();
            $table->text('mnpipditer')->nullable();
            $table->text('totalpipeth')->nullable();
            $table->text('totalotherth')->nullable();
            $table->text('totalpipth')->nullable();
            $table->text('maxmg')->nullable();
            $table->text('maxcfs')->nullable();
            $table->text('maxcoeffnt')->nullable();
            $table->text('maxin')->nullable();
            $table->text('minin')->nullable();
            $table->text('mxnode')->nullable();
            $table->text('surcharged')->nullable();
            $table->text('nodesurched')->nullable();
            $table->text('maxcrown')->nullable();
            $table->text('minbelow')->nullable();
            $table->text('flooded')->nullable();
            $table->text('flooding')->nullable();
            $table->text('floodmg')->nullable();
            $table->text('pondedvolume')->nullable();
            $table->text('maxvolume')->nullable();
            $table->text('maxperfull')->nullable();
            $table->text('maxfrecy')->nullable();
            $table->text('maxflow')->nullable();
            $table->text('maxoutfallmg')->nullable();
            $table->text('totalmg')->nullable();
            $table->text('maxpeak')->nullable();
            $table->text('maxlinkty')->nullable();
            $table->text('minpeakty')->nullable();
            $table->text('conduits')->nullable();
            $table->text('maxconduits')->nullable();
            $table->text('maxcapacity')->nullable();
            $table->text('lidstroage')->nullable();
            $table->text('snowcover')->nullable();
            $table->text('totalin')->nullable();
            $table->text('runonin')->nullable();
            $table->text('evalossin')->nullable();
            $table->text('infitionloss')->nullable();
            $table->text('surfacein')->nullable();
            $table->text('drainage')->nullable();
            $table->text('snowved')->nullable();
            $table->text('finalsnow')->nullable();
            $table->text('finalin')->nullable();
            $table->text('conerror')->nullable();
            $table->text('maxwidth')->nullable();
            $table->text('minwidth')->nullable();
            $table->text('maxarea')->nullable();
            $table->text('minarea')->nullable();
            $table->text('totalarea')->nullable();
            $table->text('results_maxflow')->nullable();
            $table->text('minflow')->nullable();
            $table->text('maxslope')->nullable();
            $table->text('minslope')->nullable();
            $table->text('subcat_maximpness')->nullable();
            $table->text('subcat_minimpness')->nullable();
            $table->text('maximpness')->nullable();
            $table->text('minimpness')->nullable();
            $table->text('subcat_maxperv')->nullable();
            $table->text('subcat_minperv')->nullable();
            $table->text('maximp')->nullable();
            $table->text('minimp')->nullable();
            $table->text('maxperv')->nullable();
            $table->text('minperv')->nullable();
            $table->text('gages')->nullable();
            $table->text('aquifers')->nullable();
            $table->text('snowpacks')->nullable();
            $table->text('unitgraphs')->nullable();
            $table->text('transects')->nullable();
            $table->text('curves')->nullable();
            $table->text('diverves')->nullable();
            $table->text('unused_pumpves')->nullable();
            $table->text('unused_ratingves')->nullable();
            $table->text('unused_shapeves')->nullable();
            $table->text('storageves')->nullable();
            $table->text('unused_tidalves')->nullable();
            $table->text('unused_weirves')->nullable();
            $table->text('unused_timeseries')->nullable();
            $table->text('timepatts')->nullable();
            $table->text('invertevsJ1')->nullable();
            $table->text('invertevsJ2')->nullable();
            $table->text('invertevsJ3')->nullable();
            $table->text('invertevsJ4')->nullable();
            $table->text('invertevsJ3_1')->nullable();
            $table->text('invertevsJ3_2')->nullable();
            $table->text('rimJ1')->nullable();
            $table->text('rimJ2')->nullable();
            $table->text('rimJ3')->nullable();
            $table->text('rimJ4')->nullable();
            $table->text('rimJ3_1')->nullable();
            $table->text('rimJ3_2')->nullable();
            $table->text('totalmgJ1')->nullable();
            $table->text('totalmgJ2')->nullable();
            $table->text('totalmgJ3')->nullable();
            $table->text('totalmgJ4')->nullable();
            $table->text('totalmgJ3_1')->nullable();
            $table->text('totalmgJ3_2')->nullable();
            $table->text('report_generate')->nullable();
            });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('weathers');
    }
}
